### ISSUE TITLE
Human-readable descriptive net name option

### ISSUE THREAD

**Issue by brianprichardson** [official-stockfish/networks#5]
Incorporating the NNUE work is wonderful.
Thank you.

While using a unique SHA net "standard" name is important, just wondering about a more human-readable descriptive option.
Perhaps another parameter in addition to
option name EvalFile type string default ./eval/nn.bin

maybe something like EvalFileDescription ?

**Comment by vondele** [comment]
this didn't happen in the last two years, the sha has been working well. If ever we update the network format, we should consider such a description. Essentially, it is best to think about the network as being part of the parameters of a binary.
